// declares variables used in the program
var currentSize = 72;
var click = 0;
var money = 0;
var previousMoney = 0;
var totalClick = 0;
var totalMoney = 0;
var totalPopped = 0;
var trial = 1;
var maxTrials = 45
var data = {'trials': []};
var random = Math.floor(Math.random() * 128 + 1);

// declares HTML tags:

// image:
var balloonImg = document.getElementById('balloon');

// text:
var poppedText = document.getElementById('popped-text');
var moneyText = document.getElementById('money');
var totalMoneyText = document.getElementById('totalMoney');
var previousMoneyText = document.getElementById('previousMoney');
var trialNumberText = document.getElementById('number');

// buttons:
var poppedButton = document.getElementById('popped-button');
var moreButton = document.getElementById('more');
var cashOutButton = document.getElementById('cashOut');

// sound:
var poppedSound = document.getElementById("explode");
var collectSound = document.getElementById("collect");

// displays numbers in form of x.xx
function displayMoney(value) {
	if (value % 100 == 0) { return value/100 + '.00'; }
	else if (value % 10 == 0) { return value/100 + '0'; }
	else { return value/100; }
}

// increases balloon size and money if the click is not equal to the randomly
// generated by value. otherwise, it resets and moves to the next trial
function onClick() {
	totalClick++;
	if (click == random) {
		// plays sound
		poppedSound.play();

		// changes variables
		totalPopped++;
		previousMoney = 0;

		// saves data
		data['trials'].push({'clicks': click, 'popped?': true, 'money': money/100});

		// changes element visiblity
		balloonImg.style.display = 'none';
		moreButton.style.display = 'none';
		cashOutButton.style.display = 'none';
		poppedText.style.display = '';
		poppedButton.style.display = '';
	}
	else if (click < random) {
		// changes variables
		currentSize += 2; 
		click++;
		money += 5;

		// changes elements
		balloonImg.style.width = currentSize + 'px';		
		moneyText.innerHTML = 'Current Balloon: $' + displayMoney(money);

		// changes element visibility
		balloonImg.style.display = '';
		poppedText.style.display = 'none';
	}
}

// cashes out of the value (adds money to totalMoney), and rests and moves to 
// the next trial
function cashOut() {
	// plays sound
	collectSound.play();

	// changes variables
	totalMoney += money
	previousMoney = money;

	// stores data
	data['trials'].push({'clicks': click, 'popped?': false, 'money': money/100});

	// changes elements
	totalMoneyText.innerHTML = 'Total Earned: $' + displayMoney(totalMoney);

	// calls reset function
	reset();
}

// if we reach the maximum number of trials, it clears out the screen and only
// shows the final money amount and number of times the balloon popped. 
// otherwise, it just rests the variables and increases the "trial" var.
function reset() {
	if (trial == maxTrials) {
		// saves data
		data['finalAmount'] = totalMoney/100;
		
		// changes elements
		trialNumberText.innerHTML = "Experiment ended.";
		moneyText.innerHTML = "Balloon pops: " + totalPopped;
		
		// hides elements
		moreButton.style.display = 'none';
		balloonImg.style.display = 'none';
		cashOutButton.style.display = 'none';
		poppedText.style.display = 'none';
		poppedButton.style.display = 'none';
	}
	else {
		// changes variables
		trial++;
		currentSize = 72;
		click = 0;
		money = 0;
		random = Math.floor(Math.random() * 128 + 1);

		// changes elements
		previousMoneyText.innerHTML = 'Earned on Previous Balloon: $' + displayMoney(previousMoney);
		trialNumberText.innerHTML = "Balloon Number: " + trial;
		balloonImg.style.width = currentSize + 'px';
		moneyText.innerHTML = 'Current Balloon: $' + displayMoney(money);

		// changes element visibility
		balloonImg.style.display = '';
		moreButton.style.display = '';
		cashOutButton.style.display = '';
		poppedText.style.display = 'none';
		poppedButton.style.display = 'none';
	}
}
