// declares variables
var currentSize = 72;
var click = 0;
var money = 0;
var previousMoney = 0;
var totalClick = 0;
var totalMoney = 0;
var totalPopped = 0;
var trial = 1;
var maxTrials = 45
var data = {'trials': []};
var random = Math.floor(Math.random() * 128 + 1);

// displays numbers in form of x.xx
function displayMoney(value) {
	if (value % 100 == 0) { return value/100 + '.00'; }
	else if (value % 10 == 0) { return value/100 + '0'; }
	else { return value/100; }
}

// increases balloon size and money if the click is not equal to the randomly
// generated by value. otherwise, it resets and moves to the next trial
function onClick() {
	totalClick++;
	if (click == random) {
		document.getElementById("explode").play();
		totalPopped++;
		data['trials'].push({'clicks': click, 'popped?': true, 'money': money/100});
		document.getElementById('balloon').style.display = 'none';
		document.getElementById('popped-text').style.display = '';
		previousMoney = 0;
		reset();
	}
	else if (click < random) {
		document.getElementById('balloon').style.display = '';
		document.getElementById('popped-text').style.display = 'none';
		currentSize += 2; 
		click++;
		document.getElementById('balloon').style.width = currentSize + 'px';		
		money += 5;
		document.getElementById('money').innerHTML = 'Current Balloon: $' + displayMoney(money);
	}
}

// cashes out of the value (adds money to totalMoney), and rests and moves to 
// the next trial
function cashOut() {
	document.getElementById("collect").play();
	totalMoney += money
	document.getElementById('totalMoney').innerHTML = 'Total Earned: $' + displayMoney(totalMoney);
	previousMoney = money;
	data['trials'].push({'clicks': click, 'popped?': false, 'money': money/100});
	reset();
}

// if we reach the maximum number of trials, it clears out the screen and only
// shows the final money amount and number of times the balloon popped. 
// otherwise, it just rests the variables and increases the "trial" var.
function reset() {
	if (trial == maxTrials) {
		data['finalAmount'] = totalMoney/100;
		document.getElementById('number').innerHTML = "Experiment ended.";
		document.getElementById('balloon').style.display = 'none';
		document.getElementById('money').innerHTML = "Balloon pops: " + totalPopped;
		document.getElementById('cashOut').style.display = 'none';
		document.getElementById('more').style.display = 'none';
	}
	else {
		trial++;
		currentSize = 72;
		click = 0;
		money = 0;
		random = Math.floor(Math.random() * 128 + 1);
		document.getElementById('previousMoney').innerHTML = 'Earned on Previous Balloon: $' + displayMoney(previousMoney);
		document.getElementById('number').innerHTML = "Balloon Number: " + trial;
		document.getElementById('balloon').style.width = currentSize + 'px';
		document.getElementById('money').innerHTML = 'Current Balloon: $' + displayMoney(money);
	}
}
